---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
      - id: detect-private-key
      - id: trailing-whitespace

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.33.0
    hooks:
      - id: markdownlint

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          - mdformat-toc
          - mdformat-frontmatter

  - repo: https://github.com/trussworks/pre-commit-hooks
    rev: v1.1.1
    hooks:
      - id: circleci-validate

  - repo: local
    hooks:
      - id: no-mdformat-toc
        name: Block mdformat TOCs
        description: This hook prevents introducing mdformat TOCs, since Docusaurus generates its own.
        entry: mdformat-toc start
        language: pygrep
        types: [markdown]
